//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Item
    {
        public int ItemID { get; set; }
        [System.ComponentModel.DisplayName("Item Name")]
        public string ItemName { get; set; }
        public string Amount { get; set; }
        [NotMapped]
        public IEnumerable<Item> GetItemList { get; set; }
        public string Price { get; set; }
    }
}
