//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Order
    {
        public int OrderID { get; set; }
        [System.ComponentModel.DisplayName("UserID")]
        public int OrderUserID { get; set; }
        [System.ComponentModel.DisplayName("Item Name")]
        public string OrderItem { get; set; }
        public string Amount { get; set; }
        public string Status { get; set; }
        public virtual User User { get; set; }
    }
}
